### ISSUE TITLE
[Bug]: PrmInfo Doesn't Provide -r Option Advertised

### ISSUE THREAD

**Issue by os-d** [Microsoft/mu_tiano_plus#220]
### Is there an existing issue for this?

- [X] I have searched existing issues

### Current Behavior

PrmInfo -? says:

![image](https://github.com/microsoft/mu_tiano_plus/assets/25697595/e1a3d268-521c-4408-81ce-8d3018aae0e4)

However, this flag is not supported:

![image](https://github.com/microsoft/mu_tiano_plus/assets/25697595/79f1f4d8-9039-439b-b695-1cfa9f898884)

### Expected Behavior

Either the `-r` flag should validate the installed PRMT ACPI table or it should not be included in the help.

### Steps To Reproduce

Boot QemuQ35Pkg in mu_tiano_platforms to the EFI shell, having included PrmInfo. Run PrmInfo as shown above.

### Build Environment

```markdown
- OS(s): EFI Shell
- Tool Chain(s): Any
- Targets Impacted: Any
```

### Version Information

```text
top of tree
```

### Urgency

Low

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by makubacki** [comment]
Patch sent to edk2 here: https://edk2.groups.io/g/devel/message/113566

Will cherry-pick to mu_tiano_plus when it's merged there.
